version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10021:10001"
    networks:
      - shared
    env_file:
      - .env
    volumes:
      - /opt/ipban/logs:/app/logs
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - .git/
            - .venv/
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: requirements.txt